spring:
  jpa:
    hibernate:
      ddl-auto: update
  flyway:
    validate-on-migrate: false
    baseline-on-migrate: true
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: password